version: "3.9"

services:
  encoder:
    build:
      context: ./encoder
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
  ingestion-api:
    build:
      context: ./ingestion-api
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_HOST=db
  ingest-worker:
    build:
      context: ./ingest-worker
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      qdrant:
        condition: service_started
      encoder:
        condition: service_started
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_HOST=db
      - QDRANT_URL=http://qdrant:6333
      - ENCODER_URL=http://encoder:8001
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - ollama
    environment:
      - QDRANT_URL=http://qdrant:6333
      - ENCODER_URL=http://encoder:8001
      - OLLAMA_URL=http://ollama:11434
  
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # Qdrant API port
      - "6334:6334" # Qdrant gRPC port (optional, but recommended for some clients)
    volumes:
      - qdrant_storage:/qdrant/storage
  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434" # Expose Ollama API port
    restart: always
  rabbitmq:
    image: rabbitmq:3.13-management-alpine # Specifies the RabbitMQ image with management plugin
    hostname: rabbitmq # Sets the hostname of the RabbitMQ container
    ports:
      - "5672:5672" # Maps RabbitMQ's default port for client connections
      - "15672:15672" # Maps RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest # Sets the default username
      RABBITMQ_DEFAULT_PASS: guest # Sets the default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persists RabbitMQ data
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  qdrant_storage:
  ollama_data:
  rabbitmq_data:
