version: "3.9"

services:
  encoder:
    build:
      context: ./encoder
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
      - ENCODER_URL=http://encoder:8001
      - OLLAMA_URL=http://ollama:11434
  
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # Qdrant API port
      - "6334:6334" # Qdrant gRPC port (optional, but recommended for some clients)
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434" # Expose Ollama API port
    restart: always

  

volumes:
  qdrant_storage:
  ollama_data:
  
