[project]
name = "rag-encoder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "fastembed>=0.7.1",
    "flask>=3.1.1",
    "pika>=1.3.2",
    "pyasyncore>=1.0.4",
]
